language: scala

scala:
  - 2.10.6
  - 2.11.7

jdk:
  # Enable once https://github.com/travis-ci/travis-ci/issues/5227 is fixed.
  #- openjdk7
  - oraclejdk7
  - oraclejdk8

before_script:
  # default $SBT_OPTS is irrelevant to sbt launcher
  - unset SBT_OPTS
  - chmod +x ./bin/travisci
  - ./bin/travisci

script:
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - bash <(curl -s https://codecov.io/bash)
